SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees WHERE SALARY NOT BETWEEN 10000 AND 15000 AND DEPARTMENT_ID = 30 OR DEPARTMENT_ID = 100;
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE FROM employees WHERE YEAR(HIRE_DATE) = 1987;
SELECT FIRST_NAME FROM employees WHERE FIRST_NAME LIKE "%b%" AND FIRST_NAME LIKE "%c%";
SELECT employees.LAST_NAME, employees.SALARY, jobs.JOB_TITLE FROM employees INNER JOIN jobs ON employees.JOB_ID = jobs.JOB_ID WHERE jobs.JOB_TITLE IN ("Programmer", "Shipping Clerk") AND employees.SALARY != 4500 AND employees.SALARY != 10000 AND employees.SALARY != 15000;
SELECT * FROM employees WHERE LAST_NAME IN ('BLAKE','SCOTT','KING','FORD');