SELECT EMPLOYEE_ID, REVERSE(SUBSTR(REVERSE(EMAIL), 4)) FROM employees;
SELECT * FROM locations WHERE LENGTH(STREET_ADDRESS) = (SELECT MIN(LENGTH(STREET_ADDRESS)) FROM locations);
SELECT FIRST_NAME, LENGTH(FIRST_NAME) FROM employees WHERE FIRST_NAME LIKE "A%" OR FIRST_NAME LIKE "J%" OR FIRST_NAME LIKE "M%" ORDER BY FIRST_NAME;